"""
C-Builder Layer cho COPL Compiler (Phase 3).
Đảm nhiệm xây dựng cấu trúc mã nhúng C an toàn, định dạng Indent, Header Guards.
"""

from typing import List, Optional

class CBuilder:
    def __init__(self, filename: str):
        self.filename = filename
        self.includes: List[str] = []
        self.macros: List[str] = []
        self.typedefs: List[str] = []
        self.prototypes: List[str] = []
        self.body: List[str] = []
        
        self.current_indent = 0
        self.indent_str = "    "
        
    def add_include(self, header: str, system: bool = True):
        if system:
            inc = f"#include <{header}>"
        else:
            inc = f'#include "{header}"'
        if inc not in self.includes:
            self.includes.append(inc)
            
    def add_macro(self, name: str, value: str):
        self.macros.append(f"#define {name} {value}")
        
    def add_typedef(self, text: str):
        self.typedefs.append(text)
        
    def add_prototype(self, proto: str):
        self.prototypes.append(proto + ";")
        
    def emit(self, code: str):
        """Xuống dòng và in code với Indent hiện tại."""
        prefix = self.indent_str * self.current_indent
        self.body.append(prefix + code)
        
    def emit_raw(self, code: str):
        """In thẳng không Indent (Dành cho raw blocks)."""
        self.body.append(code)
        
    def indent(self):
        self.current_indent += 1
        
    def dedent(self):
        if self.current_indent > 0:
            self.current_indent -= 1
            
    def render_header(self) -> str:
        """Render Text stream cho `.h` file."""
        guard = f"{self.filename.upper()}_H"
        lines = []
        lines.append(f"#ifndef {guard}")
        lines.append(f"#define {guard}\n")
        
        lines.append("/* Auto-generated by COPL Compiler */")
        lines.append("#include <stdint.h>")
        lines.append("#include <stdbool.h>\n")
        
        if self.includes:
            lines.extend(self.includes)
            lines.append("")
            
        if self.macros:
            lines.extend(self.macros)
            lines.append("")
            
        if self.typedefs:
            lines.extend(self.typedefs)
            lines.append("")
            
        if self.prototypes:
            lines.extend(self.prototypes)
            lines.append("")
            
        lines.append(f"\n#endif // {guard}")
        return "\n".join(lines)
        
    def render_source(self) -> str:
        """Render Text stream cho `.c` file."""
        lines = []
        lines.append("/* Auto-generated by COPL Compiler */")
        lines.append(f'#include "{self.filename}.h"\n')
        
        lines.extend(self.body)
        return "\n".join(lines)
